apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opnsense-dyndns-hetzner

resources:
  - deployment.yaml

configMapGenerator:
  - name: opnsense-dyndns-hetzner-config
    files:
      - config.yaml
